name: Deploy to Digital Ocean

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.DEPLOYMENT_SSH_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn run build
      
      - name: Print Current Working Directory
        run: |
          pwd
          ls

      - name: Deploy to Digital Ocean
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/next
          chmod 600 ~/.ssh/next
          ssh-keyscan 128.199.20.118 >> ~/.ssh/known_hosts

          scp -v -r -i ~/.ssh/next ./* root@128.199.20.118:frontend/



# todo: add remaining ci-cd